<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <script src="js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>

        <?php $this->addCSS('css/normalize.min.css'); ?>
        <?php $this->addCSS('css/main.css'); ?>
        <?php $this->addCSS('css/template.css'); ?>
        <?php $this->addCSS('css/mediaqueries.css'); ?>
    </head>