<?php require('includes/header.phtml'); ?>
	
    <body class="error-404">
        
        
        <header class="clearfix">
			<a class="title" href="http://leafblower.rdrkt.com" target="_blank"><img src="images/leafblower-logo.png" alt="Leafblower" /></a>
            <nav>
				<a href="/" title="Home">
					<span class="icon-home"></span>
				</a>
			</nav>
        </header>

        <main>            
			
            <h1>FOUR OH FOUR.</h1>
			<p>Sorry, the link you're looking for isn't here right now.<br />If you're sure the link is correct, please try again later.</p>
			<p>Alternatively you could go to the; <a href="/" title="Home"><span class="icon-home"></span> Home page</a>

        </main>

        <footer>
            <p class="powered">Leafblower by <a href="http://www.rdrkt.com" target="_blank" title="rdrkt">rdrkt.com</a></p>
        </footer>

        
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>            window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
        <script src="js/list.js"></script>
    </body>
</html>
