<?php require('includes/header.phtml'); ?>
	
    <body class="user-auth">
        
        <header class="clearfix">
            <a class="title" href="http://leafblower.rdrkt.com" target="_blank"><img src="images/leafblower-logo.png" alt="Leafblower" /></a>
        </header>

        <main>
            
			<form id="frmLogin" method="post" action="">
				<fieldset>
					<legend><span class="icon-lock"></span> Authentication Required</legend>
					<div class="field-wrapper clearfix">
						<label for="txtUsername">Username:</label>
						<input type="text" value="" placeholder="Your username" name="txtUsername" id="txtUsername" />
					</div>
					<div class="field-wrapper clearfix">
						<label for="txtPassword">Password:</label>
						<input type="password" value="" placeholder="******" name="txtPassword" id="txtPassword" />
					</div>
					<div class="field-wrapper clearfix">
						<a href="/recover" title="Forgotten password?" class="forgotten-password">Forgotten password?</a>
						<input type="submit" name="btnSubmit" value="Login" />
					</div>
				</fieldset>
			</form>
			
        </main>

        <footer>
            <p class="powered">Leafblower by <a href="http://www.rdrkt.com" target="_blank" title="rdrkt">rdrkt.com</a></p>
        </footer>

    </body>
</html>
