<?php require('includes/header.phtml'); ?>
	
    <body class="list-profiles">
        
        
        <header class="clearfix">
			<a class="title" href="http://leafblower.rdrkt.com" target="_blank"><img src="images/leafblower-logo.png" alt="Leafblower" /></a>
            <nav>
				<a href="/logout" title="Logout">
					<span class="icon-exit"></span>
				</a>
			</nav>
        </header>

        <main>

            <ul id="profile-list">
            <?php
                if ($jsonString = $this->getData('profile','list')) {
                    if ($profileList = json_decode($jsonString)) {
                        if ($profileList->success == 'true') {
                            foreach ($profileList->data as $key => $profile) {
                                echo '<li><a href="/view?profileId='.$profile->_id.'" title="'.$profile->name.'">'.$profile->name.'</a></li>';
                            }
                        }
                        else {
                            echo '<li>Profile list retrieval failed.</li>';
                        }
                    }
                    else {
                        echo '<li>Profile list retrieval failed.</li>';
                    }
                }
                else {
                    echo '<li>Profile list API call failed.</li>';
                }
            ?>
            </ul>

        </main>

        <footer>
            <p class="powered">Leafblower by <a href="http://www.rdrkt.com" target="_blank" title="rdrkt">rdrkt.com</a></p>
        </footer>
    </body>
</html>
