<?php require('includes/header.phtml'); ?>
	
    <body class="view-profile">
        
        <div id="loading-overlay"></div>
		<img id="loading-gif" src="images/loading.gif" alt="Loading..." title="Loading..." />

        <header class="clearfix">
			<a class="title" href="http://leafblower.rdrkt.com" target="_blank"><img src="images/leafblower-logo.png" alt="Leafblower" /></a>
            <nav>
				<a href="/logout" title="Logout">
					<span class="icon-exit"></span>
				</a>
				<a href="/" title="Home">
					<span class="icon-home"></span>
				</a>
			</nav>
        </header>

        <main class="clearfix">
            
        </main>

        <footer>
            <p class="powered">Leafblower by <a href="http://www.rdrkt.com" target="_blank" title="rdrkt">rdrkt.com</a></p>
        </footer>

        
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>            window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
        <script src="js/vendor/d3.3.1.5-min.js"></script>
        <script src="js/plugins.js"></script>
        <script src="<?php echo $apiBaseUrl; ?>:8080/socket.io/socket.io.js"></script>
		
		<?php echo $this->loadBlockResources(); ?>
		
        <script src="js/blocksController.js"></script>
        <script src="js/main.js"></script>
    </body>
</html>
